#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("BookKeeper.Resource", IsApplication=true)]

namespace BookKeeper
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040011
			public const int account_group = 2130968593;
			
			// aapt resource value: 0x7f040014
			public const int amount_excl_tax_group = 2130968596;
			
			// aapt resource value: 0x7f040017
			public const int amount_group = 2130968599;
			
			// aapt resource value: 0x7f040001
			public const int btn_account_reports = 2130968577;
			
			// aapt resource value: 0x7f04001d
			public const int btn_add_entry = 2130968605;
			
			// aapt resource value: 0x7f040021
			public const int btn_create_reports = 2130968609;
			
			// aapt resource value: 0x7f04000a
			public const int btn_date = 2130968586;
			
			// aapt resource value: 0x7f040020
			public const int btn_entry_list = 2130968608;
			
			// aapt resource value: 0x7f04001f
			public const int btn_new_entry = 2130968607;
			
			// aapt resource value: 0x7f040002
			public const int btn_tax_report = 2130968578;
			
			// aapt resource value: 0x7f040007
			public const int date_group = 2130968583;
			
			// aapt resource value: 0x7f04000b
			public const int description_group = 2130968587;
			
			// aapt resource value: 0x7f040019
			public const int ed_amount = 2130968601;
			
			// aapt resource value: 0x7f04000d
			public const int ed_description = 2130968589;
			
			// aapt resource value: 0x7f040000
			public const int lv_accountsReport = 2130968576;
			
			// aapt resource value: 0x7f04001e
			public const int lv_entries = 2130968606;
			
			// aapt resource value: 0x7f040004
			public const int radio_group = 2130968580;
			
			// aapt resource value: 0x7f040006
			public const int rb_expense = 2130968582;
			
			// aapt resource value: 0x7f040005
			public const int rb_income = 2130968581;
			
			// aapt resource value: 0x7f040013
			public const int spinner_account = 2130968595;
			
			// aapt resource value: 0x7f04001c
			public const int spinner_tax_rate = 2130968604;
			
			// aapt resource value: 0x7f040010
			public const int spinner_type = 2130968592;
			
			// aapt resource value: 0x7f040012
			public const int tv_account = 2130968594;
			
			// aapt resource value: 0x7f040018
			public const int tv_amount = 2130968600;
			
			// aapt resource value: 0x7f040015
			public const int tv_amount_excl_tax = 2130968597;
			
			// aapt resource value: 0x7f040016
			public const int tv_amount_excl_tax_value = 2130968598;
			
			// aapt resource value: 0x7f040008
			public const int tv_date = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int tv_date_result = 2130968585;
			
			// aapt resource value: 0x7f04000c
			public const int tv_description = 2130968588;
			
			// aapt resource value: 0x7f040025
			public const int tv_entry_amount = 2130968613;
			
			// aapt resource value: 0x7f040023
			public const int tv_entry_date = 2130968611;
			
			// aapt resource value: 0x7f040024
			public const int tv_entry_description = 2130968612;
			
			// aapt resource value: 0x7f040003
			public const int tv_new_entry_text = 2130968579;
			
			// aapt resource value: 0x7f040022
			public const int tv_total_tax_paid = 2130968610;
			
			// aapt resource value: 0x7f04000f
			public const int tv_type = 2130968591;
			
			// aapt resource value: 0x7f04001b
			public const int tv_vat = 2130968603;
			
			// aapt resource value: 0x7f04000e
			public const int type_group = 2130968590;
			
			// aapt resource value: 0x7f04001a
			public const int vat_group = 2130968602;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int activity_accounts_report = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int activity_create_reports = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int activity_entry = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int activity_entry_list = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int activity_main = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int activity_tax_report = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int CustomListItem = 2130837510;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030000
			public const int app_name = 2130903040;
			
			// aapt resource value: 0x7f03000f
			public const int btn_account_reports = 2130903055;
			
			// aapt resource value: 0x7f03000e
			public const int btn_add_entry = 2130903054;
			
			// aapt resource value: 0x7f030003
			public const int btn_create_reports = 2130903043;
			
			// aapt resource value: 0x7f030002
			public const int btn_entry_list = 2130903042;
			
			// aapt resource value: 0x7f030001
			public const int btn_new_entry = 2130903041;
			
			// aapt resource value: 0x7f030010
			public const int btn_tax_report = 2130903056;
			
			// aapt resource value: 0x7f030006
			public const int rb_expense = 2130903046;
			
			// aapt resource value: 0x7f030005
			public const int rb_income = 2130903045;
			
			// aapt resource value: 0x7f030015
			public const int title_accounts_report_activity = 2130903061;
			
			// aapt resource value: 0x7f030014
			public const int title_create_reports_activity = 2130903060;
			
			// aapt resource value: 0x7f030012
			public const int title_edit_entry_activity = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int title_entry_list_activity = 2130903059;
			
			// aapt resource value: 0x7f030011
			public const int title_new_entry_activity = 2130903057;
			
			// aapt resource value: 0x7f030016
			public const int title_tax_report_activity = 2130903062;
			
			// aapt resource value: 0x7f03000a
			public const int tv_account = 2130903050;
			
			// aapt resource value: 0x7f03000c
			public const int tv_amount = 2130903052;
			
			// aapt resource value: 0x7f03000b
			public const int tv_amount_excl_tax = 2130903051;
			
			// aapt resource value: 0x7f030007
			public const int tv_date = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int tv_description = 2130903048;
			
			// aapt resource value: 0x7f030004
			public const int tv_new_entry_text = 2130903044;
			
			// aapt resource value: 0x7f030009
			public const int tv_type = 2130903049;
			
			// aapt resource value: 0x7f03000d
			public const int tv_vat = 2130903053;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
